// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OtpType } from "./OtpType";

export interface SendOtpForm { emailOrPhone: string, otpType: OtpType, }